name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose the Terraform action to perform"
        required: true
        default: "plan"
        type: string
        options:
          - init
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Debug variables
      - name: Debug Variables
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}"
          echo "ENVIRONMENT=${{ secrets.ENVIRONMENT }}"

      # 4. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 5. Terraform Init
      - name: Terraform Init
        if: ${{ github.event.inputs.action == 'init' }}
        run: |
          terraform init -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" \
                         -backend-config="key=terraform/state/${{ secrets.ENVIRONMENT }}/terraform.tfstate" \
                         -backend-config="region=${{ secrets.AWS_REGION }}"

      # 6. Terraform Plan
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: |
          terraform init -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" \
                         -backend-config="key=terraform/state/${{ secrets.ENVIRONMENT }}/terraform.tfstate" \
                         -backend-config="region=${{ secrets.AWS_REGION }}" \
          terraform plan

      # 7. Terraform Apply
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform init -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" \
                         -backend-config="key=terraform/state/${{ secrets.ENVIRONMENT }}/terraform.tfstate" \
                         -backend-config="region=${{ secrets.AWS_REGION }}" \
          terraform apply -auto-approve

      # 8. Terraform Destroy
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform init -backend-config="bucket=${{ secrets.S3_BUCKET_NAME }}" \
                         -backend-config="key=terraform/state/${{ secrets.ENVIRONMENT }}/terraform.tfstate" \
                         -backend-config="region=${{ secrets.AWS_REGION }}" \
          terraform destroy -auto-approve
