name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    steps:
      # 1. Chequea el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura las credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Configura Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 4. Inicializa Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Planifica los cambios
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 6. Aplica los cambios automáticamente
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
