name: Terraform Deployment with Dynamic S3 Backend

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose the Terraform action to perform"
        required: true
        default: "plan"
        type: string
        options:
          - init
          - plan
          - apply
          - destroy

jobs:
  setup_base_resources:
    name: Setup Base Resources
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'init' || github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Base Resources)
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply (Base Resources)
        working-directory: ./terraform
        run: terraform apply -auto-approve

  create_bucket:
    name: Create S3 Bucket
    runs-on: ubuntu-latest
    needs: setup_base_resources
    outputs:
      bucket_name: ${{ steps.extract_bucket.outputs.bucket_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (S3)
        working-directory: ./terraform/
        run: terraform init

      - name: Terraform Apply (Create Bucket)
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Extract Bucket Name
        working-directory: ./terraform
        id: extract_bucket
        run: |
          bucket_name=$(terraform output -raw bucket_name)
          echo "::set-output name=bucket_name::$bucket_name"

  terraform_operations:
    name: Terraform Operations
    runs-on: ubuntu-latest
    needs: create_bucket
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init with Backend
        working-directory: ./terraform
        run: |
          terraform init -backend-config="bucket=${{ needs.create_bucket.outputs.bucket_name }}" \
                         -backend-config="key=terraform/state/${{ secrets.ENVIRONMENT }}/terraform.tfstate" \
                         -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: ./terraform
        run: terraform destroy -auto-approve
