name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecución manual
    inputs:
      action:
        description: "Choose action: apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - "apply"
          - "destroy"

jobs:
  init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debugging: List files
        run: ls -R terraform/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform -chdir=terraform init

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: init # Se asegura de que 'init' se ejecute antes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan # Se asegura de que 'plan' se ejecute antes
    if: github.event.inputs.action == 'apply'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve tfplan

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -auto-approve
