name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite ejecutar manualmente este workflow
    inputs:
      action:
        description: "Choose action: apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - "apply"
          - "destroy"

jobs:
  init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform -chdir=terraform init

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: init # Se asegura de que el job Init se ejecute primero
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan # Se asegura de que el job Plan se ejecute primero
    if: github.event.inputs.action == 'apply'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve tfplan

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -auto-approve
