name: Terraform Deployment with Dynamic S3 Backend

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose the Terraform action to perform"
        required: true
        default: "plan"
        type: string
        options:
          - init
          - plan
          - apply
          - destroy

jobs:
  create_bucket:
    name: Create S3 Bucket
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'init' }}
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 4. Initialize and Apply to Create Bucket
      - name: Terraform Init (Local State)
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply (Create Bucket)
        working-directory: ./terraform
        run: terraform apply -auto-approve

      # 5. Save Bucket Name as Output
      - name: Extract Bucket Name
        working-directory: ./terraform
        id: extract_bucket
        run: echo "::set-output name=bucket_name::$(terraform output -raw bucket_name)"

  terraform_operations:
    name: Terraform Operations
    runs-on: ubuntu-latest
    needs: create_bucket
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # 4. Initialize Backend with Dynamically Created Bucket
      - name: Terraform Init with Backend
        working-directory: ./terraform
        run: |
          terraform init -backend-config="bucket=${{ needs.create_bucket.outputs.bucket_name }}" \
                         -backend-config="key=terraform/state/${{ secrets.ENVIRONMENT }}/terraform.tfstate" \
                         -backend-config="region=${{ secrets.AWS_REGION }}"

      # 5. Terraform Plan
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      # 6. Terraform Apply
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      # 7. Terraform Destroy
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: ./terraform
        run: terraform destroy -auto-approve
